language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-de language-pack-it
install:
  - pip install -r requirements-dev.txt
script:
  - python tests/test_elementpath.py
